apiVersion: v1
kind: Pod
metadata: 
  name: db
  namespace: backend
  labels: 
    app: mysql
spec: 
  containers:
    - name: mysql
      image: mysql:latest
      env: 
        - name: MYSQL_ROOT_PASSWORD
          value: "Password123"
      ports: 
        - containerPort: 3306
      resources:
        requests: 
          cpu: 100m
          memory: 500Mi
        limits: 
          cpu: 100m
          memory: 500Mi



        # requests.cpu: "0.5"
        # requests.memory: 500Mi
        # limits.cpu: "0.5"
        # limits.memory: 500Mi