apiVersion: v1
kind: Pod
metadata: 
  name: wordpress
  namespace: frontend
spec: 
  containers: 
    - name: wordpress
      image: wordpress:latest
      env: 
        - name: WORDPRESS_DB_HOST
          value: mysql.backend.svc.cluster.local
        - name: WORDPRESS_DB_PASSWORD
          value: "Password123"
      ports: 
        - containerPort: 80
      resources:
        requests: 
          cpu: 100m
          memory: 500Mi
        limits: 
          cpu: 100m
          memory: 500Mi

