apiVersion: v1
kind: Pod
metadata:
  name: app1-pod-1
  labels: 
    app: app1
    env: dev
  namespace: app1-dev
spec: 
  containers: 
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80