apiVersion: v1
kind: ResourceQuota
metadata: 
  name: backend-quota
  namespace: backend
spec: 
  hard: 
    requests.cpu: 100m
    requests.memory: 500Mi
    limits.cpu: 100m
    limits.memory: 500Mi