apiVersion: v1
kind: ResourceQuota
metadata: 
  name: frontend-quota 
  namespace: frontend 
spec: 
  hard: 
    requests.cpu: 100m
    requests.memory: 500Mi
    limits.cpu: 100m
    limits.memory: 500Mi

